
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 12 2025 12:46:57

// Verification Directory fv/synth_wrapper 

module counter_4bit(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire n_3, n_4, n_5, n_6, n_8, n_14, n_15, n_16;
  wire n_17, n_19, n_20, n_21, n_22, n_32, n_33, n_34;
  wire n_51, n_53, n_54, n_56;
  sky130_fd_sc_hd__dfrtp_1 \p_count_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_22), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \p_count_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_21), .Q (out[2]));
  sky130_fd_sc_hd__xnor2_1 g1208(.A (n_34), .B (n_20), .Y (n_22));
  sky130_fd_sc_hd__xnor2_1 g1209(.A (n_17), .B (n_33), .Y (n_21));
  sky130_fd_sc_hd__dfrtp_1 \p_count_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_56), .Q (out[1]));
  sky130_fd_sc_hd__nand2_2 g1211(.A (n_19), .B (n_15), .Y (n_20));
  sky130_fd_sc_hd__nand3_2 g1212(.A (n_54), .B (n_53), .C (out[0]), .Y
       (n_19));
  sky130_fd_sc_hd__nand2_1 g1214(.A (n_16), .B (n_8), .Y (n_17));
  sky130_fd_sc_hd__nand2_1 g1215(.A (n_54), .B (out[0]), .Y (n_16));
  sky130_fd_sc_hd__inv_2 g1216(.A (n_14), .Y (n_15));
  sky130_fd_sc_hd__nand2_1 g1217(.A (n_8), .B (n_6), .Y (n_14));
  sky130_fd_sc_hd__dfrtp_1 \p_count_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_5), .Q (out[0]));
  sky130_fd_sc_hd__nand2_1 g1223(.A (out[2]), .B (n_51), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g1225(.A (out[1]), .B (n_51), .Y (n_8));
  sky130_fd_sc_hd__inv_1 g1227(.A (out[0]), .Y (n_5));
  sky130_fd_sc_hd__clkinv_1 g1231(.A (out[1]), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g1232(.A (out[2]), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g1243(.A (out[2]), .B (n_32), .X (n_33));
  sky130_fd_sc_hd__xor2_1 g1245(.A (out[3]), .B (n_32), .X (n_34));
  sky130_fd_sc_hd__inv_2 g1262(.A (sel), .Y (n_51));
  sky130_fd_sc_hd__nand2_1 g1263(.A (n_32), .B (n_3), .Y (n_53));
  sky130_fd_sc_hd__inv_4 g1264(.A (n_51), .Y (n_32));
  sky130_fd_sc_hd__nand2_2 g1265(.A (n_4), .B (n_32), .Y (n_54));
  sky130_fd_sc_hd__xnor3_1 g1266(.A (out[1]), .B (out[0]), .C (n_32),
       .X (n_56));
endmodule

module synth_wrapper(clk, rst_n, sel, count);
  input clk, rst_n, sel;
  output [3:0] count;
  wire clk, rst_n, sel;
  wire [3:0] count;
  wire \count_reg[0]_14 , \count_reg[1]_15 , \count_reg[2]_16 ,
       \count_reg[3]_17 , sel_reg;
  counter_4bit counter_4bit(.clk (clk), .rst_n (rst_n), .sel (sel_reg),
       .out ({\count_reg[3]_17 , \count_reg[2]_16 , \count_reg[1]_15 ,
       \count_reg[0]_14 }));
  sky130_fd_sc_hd__dfrtp_1 \count_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (\count_reg[3]_17 ), .Q (count[3]));
  sky130_fd_sc_hd__dfrtp_1 \count_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (\count_reg[2]_16 ), .Q (count[2]));
  sky130_fd_sc_hd__dfrtp_1 \count_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (\count_reg[0]_14 ), .Q (count[0]));
  sky130_fd_sc_hd__dfrtp_1 \count_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (\count_reg[1]_15 ), .Q (count[1]));
  sky130_fd_sc_hd__dfrtp_1 sel_reg_reg(.RESET_B (rst_n), .CLK (clk), .D
       (sel), .Q (sel_reg));
endmodule

